### ISSUE TITLE
Where to find Fairseq version of pretrained model

### ISSUE THREAD

**Issue by ecooper7** [utter-project/mHuBERT-147-scripts#1]
Hello, thank you very much for sharing your pretrained models and scripts!

I have a really basic question -- I can see on the HuggingFace model page's README, it is noted that there is both

> - Fairseq checkpoint (original);
> - HuggingFace checkpoint (conversion using transformers library);

I would like to use the Fairseq version of the model, not the HuggingFace one -- where can I find it?  I tried using `checkpoint_best.pt` and dropping it in directly in place of `hubert-base-ls960.pt` (pretrained HuBERT shared by Fairseq) for just some basic feature extraction from audio, but I got some errors where it seemed to be trying to download some additional files from HuggingFace, e.g.:

```
Repository Not Found for url: https://huggingface.co/facebook/checkpoint_best/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```

which makes me think that I've got a HuggingFace one by mistake -- sorry for a really basic question, but any pointers or info about how I can use mHuBERT in Fairseq instead of HuggingFace would be tremendously appreciated.  The one I downloaded and tried was from `https://huggingface.co/utter-project/mHuBERT-147/blob/main/checkpoint_best.pt`.

**Comment by mzboito** [comment]
Hello,

Many thanks for the interest in our model! :)

This is indeed the fairseq checkpoint -> https://huggingface.co/utter-project/mHuBERT-147/blob/main/checkpoint_best.pt
However, this means you need to use the **fairseq** library, and not huggingface, in order to load it. (And more specifically this fork https://github.com/utter-project/fairseq).

For instance, you can check this fairseq script for feature extraction here: 
https://github.com/utter-project/mHuBERT-147-scripts/blob/main/02_feature_extraction/extract_hubert_by_dataset.sh

**Comment by ecooper7** [comment]
Thanks so much for your quick reply!  I had been using the script `dump_hubert_feature.py` with my existing installation of Fairseq, but creating a new environment with the utter-project version of Fairseq and using that instead solved the error and I was able to successfully run mHuBERT feature extraction.
